### ISSUE TITLE
QA: 빵집등록 / 버튼이 안보이는 이슈

### ISSUE THREAD

**Issue by wooogi123** [depromeet/bread-map-front#138]
## 개요 

https://www.notion.so/depromeet/QA-6ab548db6c8445f3a89eca9192248aa5?p=2b1fb15751c34e8b9396f989b0cb7275

## 진행 사항 

- [ ] 빵집 버튼 등록의 하단고정

**Comment by HanCheo** [comment]
이부분 보니까 버튼이 `position:sticky; bottom: 16px;` 로 되어있더라구요 수정했습니다.
