### ISSUE TITLE
로그인 후 첫 화면에서 dot indicator가 하나밖에 보이지 않습니다

### ISSUE THREAD

**Issue by choi8686** [depromeet/bread-map-front#184]
![스크린샷 2021-12-31 오전 9 28 20](https://user-images.githubusercontent.com/37816932/147796443-ccc615db-6fa3-4ec1-af4e-b3760ed0629c.png)

로그인 후 첫 화면에서 dots indicator가 1개밖에 보이지 않아서 로딩 페이지로 착각하여 기다렸다가 아무런 액션이 없어 스크롤로 넘겨보니 dots indicator가 생겼습니다. 
![스크린샷 2021-12-31 오전 9 33 47](https://user-images.githubusercontent.com/37816932/147796472-95e4d86b-8e7e-4ea0-b80e-d688278e7b71.png)

확인 부탁드립니다

**Comment by HanCheo** [comment]
@choi8686
안뇽하세요 :)

저희가 급하게 출시하려고 하느라 PWA로 전황하였는데
이 부분에서 문제를 정확하게 파악하지 못해서 나타난 현상입니다 !

이번에 React-Native로 전환 예정이라 이슈 고려하겠습니다.

이슈 감사드립니당 👍

**Comment by choi8686** [comment]
@HanCheo 네 고생하십쇼!
