### ISSUE TITLE
버그 : prettier 설정이 적용 안되는 오류

### ISSUE THREAD

**Issue by HanCheo** [depromeet/bread-map-front#19]
## 개요 
ㅠ 저만 그런가요??
저는 prettier가 제대로 적용이 안되고 있었는데....

## 관련 이슈 

#15 

## 진행 사항 

- [ ] .yarn/sdks에 prettier 설정 추가

**Comment by wooogi123** [comment]
@HanCheo 패키지로는 제대로 설치되어 있는 것 같은데, 어떻게 에러가 발생하나요?

**Comment by HanCheo** [comment]
> @HanCheo 패키지로는 제대로 설치되어 있는 것 같은데, 어떻게 에러가 발생하나요?

@wooogi123 prettier modules를 찾을수가 없다구 나오네용..

찾아보니까 지금 저희 레포 ` /web/.yarn/sdks` 에 prettier 가 있어야 하는데 없어서 나타나는것 같아요.

다시 yarn berry 캐시 지우고 
`yarn dlx @yarnpkg/sdks vscode` 해주니가 prettier 내용이 sdks 에 추가되더라구요

**Comment by wooogi123** [comment]
> > @HanCheo 패키지로는 제대로 설치되어 있는 것 같은데, 어떻게 에러가 발생하나요?
> 
> 
> 
> @wooogi123 prettier modules를 찾을수가 없다구 나오네용..
> 
> 
> 
> 찾아보니까 지금 저희 레포 ` /web/.yarn/sdks` 에 prettier 가 있어야 하는데 없어서 나타나는것 같아요.
> 
> 
> 
> 다시 yarn berry 캐시 지우고 
> 
> `yarn dlx @yarnpkg/sdks vscode` 해주니가 prettier 내용이 sdks 에 추가되더라구요

prettier가 vscode extensions으로 실행될때 경로를 못잡아서 그런가보네요. 👍 👍
