### ISSUE TITLE
설정: web 프로젝트 추가 의존성 및 설정

### ISSUE THREAD

**Issue by wooogi123** [depromeet/bread-map-front#7]
## 개요 

web 프로젝트 초기 설정에서 놓친 부분 추가 수정 및 일부 코드 수정을 통한 이후 작업의 에제 코드 작성

## 관련 이슈 

#8 #9

## 진행 사항 

- [x] web/.gitignore 추가
- [x] 커밋 메세지 템플릿 추가
- [x] lint 관련 dev dependencies 설치 및 lint 환경 재정비
- [x] 기존 초기화된 프로젝트 컴포넌트 분할 및 dummy test 추가
- [x] 기본 제공되는 스타일링 구조를 emotion의 styled 구조로 간략히 수정

**Comment by HanCheo** [comment]
gitignore 파일ㅠㅠ
제가 넣을께용

**Comment by wooogi123** [comment]
> gitignore 파일ㅠㅠ
> 제가 넣을께용

#8 이슈 assign 해놓았습니다! 이걸로 pr 올려주세용

**Comment by HanCheo** [comment]
옙!
