### ISSUE TITLE
메인, 데모 페이지 코드 통합 및 공용 카테고리 리스트 컴포넌트 통합

### ISSUE THREAD

**Issue by wooogi123** [depromeet/bread-map-front#98]
## 진행 사항 

- [x] 메인, 데모 페이지 코드 통합
- [ ] 카테고리 리스트 컴포넌트 통합

**Comment by HanCheo** [comment]
맵화면 드래그로 안움직이는게 이슈로 있는데 변경하셔두 되구
`component/daedong/DaedongMap/index.tsx`에서 `MapButtonWrapper`스타일 컴포넌트에 `pointer-events: none;`넣어주심 됩니다!
